version: '3.7'
services:
  wall:
    image: wall
    build: .
    command:
      - start-dev
    env_file:
      - keycloack.env
    volumes:
        - ~/.postgresql/root.crt:/opt/keycloak/.postgresql/root.crt
    ports:
      - 8443:8443
      - 8080:8080
  db:
    image: postgres:14-alpine
    environment:
        POSTGRES_DB: wall
        POSTGRES_PASSWORD: root
    volumes:
        - pg-data:/var/lib/postgresql/data
    ports:
        - 5432:5432
volumes:
  pg-data: